
# Generated by Django 2.0.4 on 2018-05-01 06:17

from django.db import migrations, models

# Generated by Django 2.0.3 on 2018-05-01 02:30

from django.db import migrations, models
import django.utils.timezone



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('login_aluno', models.CharField(max_length=50, unique=True)),
                ('senha_aluno', models.CharField(max_length=70)),
                ('nome_aluno', models.CharField(max_length=100)),
                ('email_aluno', models.CharField(max_length=70, unique=True)),
                ('celular_aluno', models.IntegerField(unique=True)),
                ('dt_expiracao_aluno', models.DateField()),
                ('ra_aluno', models.IntegerField(unique=True)),
                ('foto_aluno', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_aluno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id_coordenador', models.AutoField(primary_key=True, serialize=False)),
                ('login_coordenador', models.CharField(max_length=50, unique=True)),
                ('senha_coordenador', models.CharField(max_length=50)),
                ('nome_coordenador', models.CharField(max_length=100)),
                ('email_coordenador', models.CharField(max_length=70, unique=True)),
                ('celular_coordenador', models.IntegerField(unique=True)),
                ('dt_expiracao_coordenador', models.DateField()),
            ],
            options={
                'db_table': 'tbl_cordenador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id_mensagem', models.AutoField(primary_key=True, serialize=False)),
                ('assunto_mensagem', models.CharField(max_length=50)),
                ('referencia_mensagem', models.CharField(max_length=50)),
                ('conteudo_mensagem', models.CharField(max_length=60)),
                ('status_mensagem', models.CharField(max_length=30)),

                ('dt_envio_mensagem', models.DateField()),

                ('dt_envio_mensagem', models.DateField(default=django.utils.timezone.now)),

                ('dt_resposta_mensagem', models.DateField(blank=True, null=True)),
                ('resposta_mensagem', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_mensagem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id_professor', models.AutoField(primary_key=True, serialize=False)),
                ('login_professor', models.CharField(max_length=50, unique=True)),
                ('senha_professor', models.CharField(max_length=50)),
                ('nome_professor', models.CharField(max_length=100)),
                ('email_professor', models.CharField(max_length=70, unique=True)),
                ('celular_professor', models.IntegerField(unique=True)),
                ('dt_expiracao_professor', models.DateField()),
                ('apelido_professor', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'tbl_professor',
                'managed': False,
            },
        ),
    ]
